name: DonationMeter
main: fghjconner.DonationMeter.DonationMeter
version: 0.4
commands:
    DonationMeter:
        description: Displays donation status
        usage: /DonationMeter help for commands
        aliases: [Donations]
