name: DonationMeter
main: fghjconner.DonationMeter.DonationMeter
version: 0.3
commands:
    DonationMeter:
        description: Displays donation status
        usage: /Donations help for commands
    Donations:
        description: Displays donation status
        usage: /Donations help for commands